name: Development
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: alpine
            conda_ver: 4.12.0
            py_ver: '3.10'
            platform: linux/amd64
            py_label: py39_
            conda_md5: 4e2f31e0b2598634c80daa12e4981647
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.9
            platform: linux/amd64
            py_label: py39_
            conda_md5: 8c69f65a4ae27fb41df0fe552b4a8a3b
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.8
            platform: linux/amd64
            py_label: py38_
            conda_md5: 14da4a9a44b337f7ccb8363537f65b9c
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.7
            platform: linux/amd64
            py_label: py37_
            conda_md5: 9f186c1d86c266acc47dbc1603f0e2ed
          - distro: alpine
            conda_ver: 4.5.4
            py_ver: 3.6
            platform: linux/amd64
            conda_md5: a946ea1d0c4a642ddf0c3a26a18bb16d
          - distro: debian
            conda_ver: 4.12.0
            py_ver: '3.10'
            platform: linux/amd64
            py_label: py39_
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.9
            platform: linux/amd64
            py_label: py39_
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.8
            platform: linux/amd64
            py_label: py38_
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.7
            platform: linux/amd64
            py_label: py37_
          - distro: debian
            conda_ver: 4.5.4
            py_ver: 3.6
            platform: linux/amd64
          # - distro: debian
          #   conda_ver: 4.10.3
          #   py_ver: 3.9
          #   platform: linux/arm64
          #   py_label: py39_
          # - distro: debian
          #   conda_ver: 4.10.3
          #   py_ver: 3.8
          #   platform: linux/arm64
          #   py_label: py38_
          # - distro: debian
          #   conda_ver: 4.10.3
          #   py_ver: 3.7
          #   platform: linux/arm64
          #   py_label: py37_
    env:
      DISTRO: ${{matrix.distro}}
      CONDA_VER: ${{matrix.conda_ver}}
      PY_VER: ${{matrix.py_ver}}
      PLATFORM: ${{matrix.platform}}
      PY_LABEL: ${{matrix.py_label}}
      CONDA_MD5: ${{matrix.conda_md5}}
      DOCKER_CLIENT_TIMEOUT: "120"
      COMPOSE_HTTP_TIMEOUT: "120"
    steps:
      - uses: actions/checkout@v2
      - name: Determine platform tag
        run: |
          PLATFORM_TAG=$(echo "$PLATFORM" | tr '/' '_')
          echo "PLATFORM_TAG=${PLATFORM_TAG}" >> $GITHUB_ENV
      - uses: dbhi/qus/action@main
        with:
          targets: aarch64
      # - name: Set up QEMU
      #   id: qemu
      #   uses: docker/setup-qemu-action@v1
      #   with:
      #     image: tonistiigi/binfmt:latest
      #     platforms: all
      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1
      - name: Compile image
        run: |
          docker buildx bake -f dist/${DISTRO}/docker-compose.yaml \
              --set *.platform=${PLATFORM} --set *.context=. --load
          REF=$(eval "echo $(cat dist/${DISTRO}/docker-compose.yaml | grep 'image:' | \
              awk '{print $2}')")
          docker save "${REF}" | \
              gzip > "${CONDA_VER}-py${PY_VER}-${DISTRO}-${PLATFORM_TAG}.tar.gz"
      - name: Add image artifact
        uses: actions/upload-artifact@v2
        with:
          name: >
            ${{format('{0}-py{1}-{2}-{3}', matrix.conda_ver, matrix.py_ver, matrix.distro,
                      env.PLATFORM_TAG)}}
          path: >
            ${{format('{0}-py{1}-{2}-{3}.tar.gz', matrix.conda_ver, matrix.py_ver,
                      matrix.distro, env.PLATFORM_TAG)}}
          retention-days: 1
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: alpine
            conda_ver: 4.12.0
            py_ver: '3.10'
            platform: linux/amd64
            package_manager: apk
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.9
            platform: linux/amd64
            package_manager: apk
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.8
            platform: linux/amd64
            package_manager: apk
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.7
            platform: linux/amd64
            package_manager: apk
          - distro: alpine
            conda_ver: 4.5.4
            py_ver: 3.6
            platform: linux/amd64
            package_manager: apk
          - distro: debian
            conda_ver: 4.12.0
            py_ver: '3.10'
            platform: linux/amd64
            package_manager: apt
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.9
            platform: linux/amd64
            package_manager: apt
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.8
            platform: linux/amd64
            package_manager: apt
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.7
            platform: linux/amd64
            package_manager: apt
          - distro: debian
            conda_ver: 4.5.4
            py_ver: 3.6
            platform: linux/amd64
            package_manager: apt
          # - distro: debian
          #   conda_ver: 4.10.3
          #   py_ver: 3.9
          #   platform: linux/arm64
          #   package_manager: apt
          # - distro: debian
          #   conda_ver: 4.10.3
          #   py_ver: 3.8
          #   platform: linux/arm64
          #   package_manager: apt
          # - distro: debian
          #   conda_ver: 4.10.3
          #   py_ver: 3.7
          #   platform: linux/arm64
          #   package_manager: apt
    env:
      DISTRO: ${{matrix.distro}}
      CONDA_VER: ${{matrix.conda_ver}}
      PY_VER: ${{matrix.py_ver}}
      PLATFORM: ${{matrix.platform}}
      PACKAGE_MANAGER: ${{matrix.package_manager}}
    steps:
      - uses: actions/checkout@v2
      - name: Determine platform tag
        run: |
          PLATFORM_TAG=$(echo "$PLATFORM" | tr '/' '_')
          echo "PLATFORM_TAG=${PLATFORM_TAG}" >> $GITHUB_ENV
      - name: Fetch image artifact
        uses: actions/download-artifact@v2
        with:
          name: >
            ${{format('{0}-py{1}-{2}-{3}', matrix.conda_ver, matrix.py_ver, matrix.distro,
                      env.PLATFORM_TAG)}}
      - uses: dbhi/qus/action@main
        with:
          targets: aarch64
      - name: Run integration tests
        run: |
          export HOST_UID=$(id -u)
          docker load < "${CONDA_VER}-py${PY_VER}-${DISTRO}-${PLATFORM_TAG}.tar.gz"
          tests/main.sh
  publish:
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/master' &&
      (
        github.repository_owner == 'datajoint' ||
        github.repository_owner == 'datajoint-company'
      )
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - distro: alpine
            conda_ver: 4.12.0
            py_ver: '3.10'
            platform: linux/amd64
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.9
            platform: linux/amd64
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.8
            platform: linux/amd64
          - distro: alpine
            conda_ver: 4.10.3
            py_ver: 3.7
            platform: linux/amd64
          - distro: alpine
            conda_ver: 4.5.4
            py_ver: 3.6
            platform: linux/amd64
          - distro: debian
            conda_ver: 4.12.0
            py_ver: '3.10'
            platform: linux/amd64
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.9
            platform: linux/amd64
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.8
            platform: linux/amd64
          - distro: debian
            conda_ver: 4.10.3
            py_ver: 3.7
            platform: linux/amd64
          - distro: debian
            conda_ver: 4.5.4
            py_ver: 3.6
            platform: linux/amd64
          # - distro: debian
          #   conda_ver: 4.10.3
          #   py_ver: 3.9
          #   platform: linux/arm64
          # - distro: debian
          #   conda_ver: 4.10.3
          #   py_ver: 3.8
          #   platform: linux/arm64
          # - distro: debian
          #   conda_ver: 4.10.3
          #   py_ver: 3.7
          #   platform: linux/arm64
    env:
      DISTRO: ${{matrix.distro}}
      CONDA_VER: ${{matrix.conda_ver}}
      PY_VER: ${{matrix.py_ver}}
      PLATFORM: ${{matrix.platform}}
      DOCKER_USERNAME: ${{secrets.docker_username}}
      DOCKER_PASSWORD: ${{secrets.docker_password}}
    steps:
      - uses: actions/checkout@v2
      - name: Determine platform tag
        run: |
          PLATFORM_TAG=$(echo "$PLATFORM" | tr '/' '_')
          echo "PLATFORM_TAG=${PLATFORM_TAG}" >> $GITHUB_ENV
      - name: Fetch image artifact
        uses: actions/download-artifact@v2
        with:
          name: >
            ${{format('{0}-py{1}-{2}-{3}', matrix.conda_ver, matrix.py_ver, matrix.distro,
                      env.PLATFORM_TAG)}}
      - name: Publish image
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker load < "${CONDA_VER}-py${PY_VER}-${DISTRO}-${PLATFORM_TAG}.tar.gz"
          REF=$(eval "echo $(cat dist/${DISTRO}/docker-compose.yaml | grep 'image:' | \
              awk '{print $2}')")
          TAG=$(echo $REF | awk -F':' '{print $2}')
          IMAGE=$(echo $REF | awk -F':' '{print $1}')
          docker push "${IMAGE}:${TAG}"
          docker tag "${IMAGE}:${TAG}" "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
          docker push "${IMAGE}:${TAG}-${GITHUB_SHA:0:7}"
          [ "$PY_VER" == "3.9" ] && [ "$DISTRO" == "debian" ] \
                  && docker tag "${IMAGE}:${TAG}" "${IMAGE}:latest" \
                  && docker push "${IMAGE}:latest" \
              || echo "skipping 'latest' tag..."
  publish-docs:
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/master' &&
      (
        github.repository_owner == 'datajoint' ||
        github.repository_owner == 'datajoint-company'
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      # - name: Upload docs artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: docs-html
      #     path: docs/_build/html/
      #     retention-days: 1
      - name: Commit documentation changes
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git \
              --branch gh-pages --single-branch gh-pages
          rm -R gh-pages/*
          cp -r docs/_build/html/* gh-pages/
          cp .gitignore gh-pages/
          touch gh-pages/.nojekyll
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add . --all
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{secrets.GITHUB_TOKEN}}